### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by OmarHamdoun** [buzkent86/paper#2]
[ 40%] Linking CXX executable EnKCF
CMakeFiles/EnKCF.dir/main/src/runtracker.cpp.o: In function `main':
runtracker.cpp:(.text.startup+0x1d6c): undefined reference to `cameraMotionModel(cv::Mat, cv::Mat)'
collect2: error: ld returned 1 exit status
CMakeFiles/EnKCF.dir/build.make:145: recipe for target 'EnKCF' failed
make[2]: *** [EnKCF] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/EnKCF.dir/all' failed
make[1]: *** [CMakeFiles/EnKCF.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ArmstrongYang** [comment]
The same error to me:
Ubuntu 16.04

EnKCF_Tracker/C++_Implementation/build $ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /usr/local (found version "3.4.0")
-- Configuring done
-- Generating done
-- Build files have been written to: 
EnKCF_Tracker/C++_Implementation/build $ make -j8
Scanning dependencies of target EnKCF
[ 20%] Building CXX object CMakeFiles/EnKCF.dir/tracker/src/Function_Definitions.cpp.o
[ 40%] Building CXX object CMakeFiles/EnKCF.dir/detector/src/fhog.cpp.o
[ 60%] Building CXX object CMakeFiles/EnKCF.dir/main/src/runtracker.cpp.o
[ 80%] Building CXX object CMakeFiles/EnKCF.dir/detector/src/kcftracker.cpp.o
[100%] Linking CXX executable EnKCF
CMakeFiles/EnKCF.dir/main/src/runtracker.cpp.o: In function `main':
runtracker.cpp:(.text.startup+0x1e6b): undefined reference to `cameraMotionModel(cv::Mat, cv::Mat)'
collect2: error: ld returned 1 exit status
CMakeFiles/EnKCF.dir/build.make:210: recipe for target 'EnKCF' failed
make[2]: *** [EnKCF] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/EnKCF.dir/all' failed
make[1]: *** [CMakeFiles/EnKCF.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by uzkent** [comment]
@OmarHamdoun @ArmstrongYang Not really sure why this is happening. It probably does not search for the `cameraMotionModel` function in [here](https://github.com/buzkent86/EnKCF_Tracker/blob/master/C%2B%2B_Implementation/main/include/findHom.hpp). You do not need to remove camera motion unless there is drastic ego-motion in between successive frames. You can simply remove https://github.com/buzkent86/EnKCF_Tracker/blob/3513ffc42a988a0960319188252162846456b93e/C%2B%2B_Implementation/main/src/runtracker.cpp#L309 and it should work fine.

**Comment by JanKrcek-zz** [comment]
@buzkent86 Hello, let me suggest a permanent fix. One way to do it, is to update the [CMakeLists.txt ](https://github.com/buzkent86/EnKCF_Tracker/blob/master/C%2B%2B_Implementation/CMakeLists.txt)lines 16 and 18 as follows:  
`FILE(GLOB_RECURSE sourcefiles ./detector/src/kcftracker.cpp ./detector/src/fhog.cpp ./tracker/src/Function_Definitions.cpp ./main/src/findHom.cpp ./main/src/runtracker.cpp)`  
and  
`INCLUDE_DIRECTORIES(./detector/include/ ./tracker/include/ ./main/include/)`

And lastly change the relative path import in runtracker.cpp, line 8 to:
`#include "findHom.hpp"`

This allows the build to run without errors for me. Cheers!

**Comment by uzkent** [comment]
@JanKrcek Thanks for your suggestion. Again, estimating camera motion slows down the tracker. It should be removed if the speed is priority.
