### ISSUE TITLE
track result is poor

### ISSUE THREAD

**Issue by anhuipl2010** [buzkent86/paper#3]
I try it on UAV123 dataset, I found it's poor.Is some vars need to be changed?

**Comment by uzkent** [comment]
@anhuipl2010 Can you please share your branch with me so that I can inspect it? And how poor is the performance compared to the results highlighted in the paper?

**Comment by anhuipl2010** [comment]
https://github.com/anhuipl2010/EnKCF_Tracker/tree/master/PL_fix

**Comment by anhuipl2010** [comment]
your version can not run. I had fixed some places.I just run it for dataset bike1 car in UAV123  and etc. The result is not good.But eco tracking performance good.You can check it.Maybe i have some errors.
