### ISSUE TITLE
 fatal error: opencv2/xfeatures2d.hpp: No such file or directory

### ISSUE THREAD

**Issue by copperwiring** [buzkent86/paper#4]
While building the code, I see: 

`EnKCF_Tracker/C++_Implementation/main/src/findHom.cpp:7:10: fatal error: opencv2/xfeatures2d.hpp: No such file or directory
`
I see this might be an opencv issue. Did you separately download it?

**Comment by uzkent** [comment]
@copperwiring Sorry for the late response. https://github.com/buzkent86/EnKCF_Tracker/issues/2 This should answer your question.

**Comment by aminmardani** [comment]
I have same error how can i fix ?

**Comment by uzkent** [comment]
@aminmardani what is your opencv version?

**Comment by aminmardani** [comment]
3.4.2
